export const speciesContents = [
  "adonidia palm",
  "african milk tree",
  "african violet",
  "agave geminiflora",
  "aglaonema red vein",
  "air plant",
  "algerian ivy",
  "alocasia azlanii",
  "alocasia black velvet",
  "alocasia lutea golden",
  "alocasia pink dragon",
  "alocasia polly",
  "alocasia purple sword",
  "aloe blush",
  "aloe jucunda",
  "aloe pepe ",
  "aloe sunset",
  "aloe vera",
  "aloe white fox",
  "ant plant",
  "anthurium big and bold",
  "anthurium pink",
  "anthurium red",
  "anthurium ruffles",
  "areca palm",
  "arrowhead plant",
  "asparagus fern",
  "autumn fern",
  "avocado tree",
  "bamboo palm",
  "basil",
  "bird of paradise",
  "bird's nest fern",
  "bishop's cap cactus",
  "bromeliad aechmea pink",
  "bromeliad christiane",
  "bromeliad electra",
  "bromeliad fiesta",
  "bromeliad guzmania 2000",
  "bromeliad guzmania lydia",
  "bromeliad guzmania sky",
  "bromeliad miranda",
  "bromeliad pineapple",
  "bromeliad ritmo",
  "bromeliad vogue",
  "bromeliad vriesea cathy",
  "bromeliad vriesea splenriet",
  "bromeliad vriesea tosca",
  "bullwinkle cactus",
  "burgundy rubber tree",
  "butterfly plant",
  "button fern",
  "caladium",
  "calathea beauty star",
  "calathea dottie",
  "calathea freddie",
  "calathea medallion",
  "calathea misto",
  "calathea musaica",
  "calathea peacock",
  "calathea pinstripe",
  "calathea rattlesnake",
  "calathea rosy roseo",
  "calathea vittata",
  "calathea white flame",
  "calathea zebra",
  "callisia pink panther",
  "canary island ivy",
  "candelabra cactus",
  "carnivorous trumpet pitcher judith hindle",
  "carnivorous venosa red",
  "carnivorous venus fly trap",
  "cast iron plant",
  "cat grass",
  "cat palm",
  "catnip",
  "cebu blue pothos",
  "chamomile",
  "chinese fan palm",
  "chives onion",
  "cilantro",
  "coconut palm",
  "coffee plant",
  "cordyline",
  "crassula calico kitten",
  "crassula cephalophora",
  "crocodile fern",
  "croton magnificent",
  "croton petra",
  "cryptanthus earth star absolute zero",
  "cryptanthus earth star pink",
  "cryptanthus earth star red",
  "ctenanthe lubbersiana",
  "cutlass aglaonema",
  "date palm",
  "dieffenbachia",
  "domino peace lily",
  "dracaena colorama",
  "dracaena dorado",
  "dracaena elegance",
  "dracaena fragrans",
  "dracaena giganta",
  "dracaena gold star",
  "dracaena green jewel",
  "dracaena jade jewel",
  "dracaena janet craig",
  "dracaena lemon lime",
  "dracaena limelight",
  "dracaena magenta braid",
  "dracaena marginata bush",
  "dracaena marginata open weave",
  "dracaena rikki cane ",
  "dracaena sol",
  "dracaena song of india",
  "dracaena song of jamaica",
  "dracaena tarzan",
  "dracaena twister",
  "dracaena warneckii",
  "dwarf banana tree",
  "dwarf chin cactus",
  "dyckia grape jelly ",
  "east indian holly fern",
  "easter lily",
  "easter lily cactus",
  "echeveria filiferum",
  "echeveria rosea",
  "emerald ripple cactus",
  "emina fern",
  "english ivy",
  "english ivy 'glacier'",
  "euonymus",
  "fairy castle cactus",
  "fatsia japonica",
  "ficus alii",
  "ficus altissima",
  "ficus audrey",
  "ficus benjamina",
  "ficus danielle",
  "ficus ginseng",
  "ficus little fiddle",
  "ficus lyrata bonsai",
  "ficus repens green",
  "ficus spire",
  "ficus tineke",
  "ficus umbellata",
  "fiddle leaf fig",
  "fiddle leaf fig column",
  "fishbone cactus",
  "fishbone prayer plant",
  "fishtail palm",
  "fittonia",
  "flowering kalanchoe",
  "footed blue star fern",
  "foxtail fern",
  "fuchsia",
  "fuzzy petiole",
  "gardenia",
  "gasteria liliputana",
  "goeppertia orbifolia",
  "golden barrel cactus",
  "golden pothos",
  "goldfish plant",
  "green hoya",
  "green oxalis",
  "hawaiian pothos",
  "haworthia",
  "hedge cactus",
  "hedgehog aloe",
  "homalomena emerald gem",
  "hoya compacta",
  "hoya curtisii",
  "hoya heart",
  "hoya kentiana",
  "hoya krimson princess ",
  "hoya krimson queen",
  "hoya krohniana",
  "hoya lisa",
  "hoya macrophylla",
  "hoya pachyclada",
  "hoya retusa",
  "hypoestes",
  "indo princess aglaonema",
  "jade plant",
  "jade pothos",
  "japanese sago palm",
  "kalanchoe flapjack",
  "kale storm",
  "kangaroo fern",
  "kimberly queen fern",
  "lace aloe",
  "lace aloe",
  "lady finger cactus",
  "lantana cactus",
  "lavender",
  "lavender tree",
  "lemon balm",
  "lemon button fern",
  "lemon cypress",
  "lemon tree",
  "lemongrass",
  "life saver cactus",
  "lipstick plant",
  "lithops",
  "lucky bamboo",
  "lucky bamboo",
  "madagascar palm",
  "mahogany fern",
  "maidenhair blush fern",
  "maidenhair fern",
  "maidenhair oceanspray fern",
  "majesty palm",
  "mandevilla",
  "marble queen pothos",
  "mint",
  "money maker",
  "money tree",
  "monstera",
  "monstera adansonii",
  "monstera dubia",
  "monstera sp. ‘peru’",
  "monstera standleyana albo",
  "moon cactus",
  "neon pothos",
  "neon prayer plant",
  "nepenthes pitcher plant",
  "norfolk pine",
  "norfolk pine",
  "old lady cactus",
  "old man cactus",
  "orange mint",
  "orange tree",
  "orchid",
  "oregano",
  "oxalis",
  "panda plant",
  "parlor palm",
  "parsley",
  "peace lily",
  "peanut cactus",
  "pearls and jade pothos",
  "pearls n joy pothos",
  "pencil cactus",
  "peperomia cupid",
  "peperomia frost",
  "peperomia ginny",
  "peperomia green",
  "peperomia happy bean",
  "peperomia hope",
  "peperomia obtusifolia variegated",
  "peperomia piper",
  "peperomia pixie lime",
  "peperomia quito",
  "peperomia rosso",
  "peperomia ruby glow",
  "peperomia schumi red",
  "peperomia watermelon",
  "pepper plant",
  "philodendron birkin",
  "philodendron brandi",
  "philodendron brasil",
  "philodendron heartleaf",
  "philodendron hope selloum",
  "philodendron lemon lime",
  "philodendron little hope",
  "philodendron micans velvet",
  "philodendron pink princess",
  "philodendron prince of orange",
  "philodendron shangri la",
  "philodendron silver sword",
  "philodendron velvet",
  "philodendron white knight",
  "philodendron xanadu",
  "pigtail palm",
  "pilea",
  "pilea baby tears",
  "pincushion cactus",
  "pineapple sage",
  "pink aglaonema",
  "pink dalmatian aglaonema",
  "pink splash aglaonema",
  "plerandra elegantissima",
  "plerandra elegantissima ‘bianca’",
  "poinsettia",
  "poinsettia",
  "polka dot begonia ",
  "polyscias scutellaria",
  "ponytail palm",
  "prickly pear cactus",
  "princess pine",
  "purple heart tradescantia",
  "purple passion plant",
  "purple perle",
  "purple waffle plant",
  "rabbit foot fern",
  "red aglaonema",
  "red balloon barrel cactus",
  "red bromeliad guzmania",
  "red prayer plant",
  "rhaphidophora ",
  "rhapis palm",
  "rhoeo oyster",
  "rosemary",
  "sage",
  "samurai sansevieria",
  "sansevieria",
  "sansevieria cylindrica",
  "sansevieria golden hahnii",
  "sansevieria moonshine",
  "sansevieria sayuri",
  "sarracenia pitcher plant",
  "schefflera amate",
  "schefflera arboricola",
  "scindapsus jade satin",
  "scindapsus moonlight",
  "sedum stonecrop",
  "sensitive plant",
  "silver bay aglaonema",
  "silver lace fern",
  "silver lady fern",
  "silver ribbon fern",
  "silver satin pothos",
  "silver satin pothos",
  "silver squill",
  "speckled hoya",
  "spider plant",
  "spring snow aglaonema",
  "staghorn fern",
  "stevia",
  "string of bananas",
  "string of dolphins",
  "string of hearts",
  "string of pearls",
  "string of pickles",
  "string of turtles ",
  "stromanthe peacock",
  "stromanthe triostar",
  "sundew",
  "swedish ivy",
  "tahitian bridal veil ",
  "thyme",
  "tillandsia summer",
  "tomato plant",
  "torch cactus",
  "tradescantia nanouk",
  "tradescantia zebrina",
  "trailing jade",
  "variegated croton ",
  "variegated ficus",
  "variegated schefflera arboricola",
  "whale fin sansevieria",
  "yucca cane",
  "zebra plant",
  "zenzi plant",
  "zygo cactus",
  "zz plant",
];
